services:
  postgres:
    image: postgres:16
    container_name: db
    env_file:
      - ./postgresql/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
      - ./postgresql/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf", "-c", "listen_addresses=*"]
    networks:
      - myrafeeq_network
    restart: unless-stopped

volumes:
  db_data:

networks:
  myrafeeq_network:
